# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-21 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20171021_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='friend_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='friend',
            name='last_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
